export const AUTH = {
  SIGNED_IN: "SIGNED_IN",
  SIGNED_OUT: "SIGNED_OUT",
  USER_PROFILE: "USER_PROFILE",
  USER_INFO: "USER_INFO",
  PAYMENTS: "PAYMENTS",
  REMOVE_PAYMENTS: "REMOVE_PAYMENTS",
  OPEN_LOGIN_MODAL: "OPEN_LOGIN_MODAL",
  CLOSE_LOGIN_MODAL: "CLOSE_LOGIN_MODAL",
  REMOVE_GALLERY: "REMOVE_GALLERY",
  OPEN_FORGOT_PASSWORD_MODAL: "OPEN_FORGOT_PASSWORD_MODAL",
  CLOSE_FORGOT_PASSWORD_MODAL: "CLOSE_FORGOT_PASSWORD_MODAL"
}

export const STRIPE = {
  OPEN_STRIPE_MODAL: "OPEN_STRIPE_MODAL",
  CLOSE_STRIPE_MODAL: "CLOSE_STRIPE_MODAL",
}

export const COMMON = {
  TOSTIFY_ALERT_CLEAR: "TOSTIFY_ALERT_CLEAR",
  TOSTIFY_ALERT: "TOSTIFY_ALERT",
  SET_SEARCH: "SET_SEARCH"
}

export const WORKOUT = {
  WORKOUT_SESSIONS: "WORKOUT_SESSIONS",
  UPDATE_SESSION: "UPDATE_SESSION",
  DELETE_SESSION: "DELETE_SESSION",
  REFUND_WORKOUT: "REFUND_WORKOUT",
  ADD_RATE: "ADD_RATE",
}
export const INSTAGRAM = {
  INSTAGRAM_FEED: "INSTAGRAM_FEED",
}

export const FUNDS = {
  FETCH_FUNDS: "FETCH_FUNDS",
  FUND_WITHDRAW: 'FUND_WITHDRAW',
  FETCH_FUNDS_SUMMARY: 'FETCH_FUNDS_SUMMARY'
}

